<!DOCTYPE html>
<html lang="es"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Roles y permisos | Hospital Nuestra Señora de las Mercedes</title>@vite(['resources/css/app.css','resources/js/app.js'])</head>
<body><div class="settings-page roles-page"><header class="report-page-header"><a class="settings-header-action settings-header-action--back" href="{{ route('portal','administrador') }}" aria-label="Volver al panel de administración"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M19 12H5m6-6-6 6 6 6"/></svg><span>Volver al panel</span></a><strong>Roles y permisos</strong><a class="settings-header-action settings-header-action--next" href="{{ route('admin.users') }}" aria-label="Ir a usuarios"><span>Usuarios</span><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M5 12h14m-6-6 6 6-6 6"/></svg></a></header><main>
@if(session('success'))<div class="success-banner">✓ {{ session('success') }}</div>@endif @if($errors->any())<div class="auth-error">{{ $errors->first() }}</div>@endif
<div class="admin-heading"><div><p>CONTROL DE ACCESO</p><h1>Usuarios, roles y permisos</h1><span>Crea usuarios y define exactamente lo que pueden usar en el sistema.</span></div></div>
<section class="roles-layout">
<section class="role-surface create-user-card"><div class="role-section-head"><span class="role-step">1</span><div><h2>Crear usuario</h2><p>La cuenta se crea activa con el rol seleccionado.</p></div></div><form method="POST" action="{{ route('admin.roles.users.store') }}" class="role-form ajax-form" data-reset-on-success="1">@csrf<label>Nombre completo<input name="name" value="{{ old('name') }}" required placeholder="Ej. Ana María López"></label><div class="role-form-grid"><label>Correo institucional<input type="email" name="email" value="{{ old('email') }}" required placeholder="usuario@hospital.gob.pe"></label><label>Usuario<input name="username" value="{{ old('username') }}" placeholder="ana.lopez"></label></div><div class="role-form-grid"><label>Contraseña inicial<input type="password" name="password" required minlength="8" placeholder="Mínimo 8 caracteres"></label><label>Confirmar contraseña<input type="password" name="password_confirmation" required minlength="8"></label></div><label>Rol personalizado<select id="userCreateRole" name="custom_role_id" required @disabled($assignableRoles->isEmpty())>@if($assignableRoles->isEmpty())<option value="">Crea primero un rol</option>@else<option value="" disabled selected>Seleccionar rol</option>@foreach($assignableRoles as $role)<option value="{{ $role->id }}" @selected(old('custom_role_id')==$role->id)>{{ $role->name }}</option>@endforeach @endif</select></label><button class="login-primary" @disabled($assignableRoles->isEmpty())><svg viewBox="0 0 24 24" width="13" height="13" fill="none" stroke="currentColor" stroke-width="3" stroke-linecap="round" stroke-linejoin="round"><line x1="12" y1="5" x2="12" y2="19"></line><line x1="5" y1="12" x2="19" y2="12"></line></svg>Crear usuario y asignar rol</button></form></section>
 <section class="role-surface"><div class="role-section-head"><span class="role-step">2</span><div><h2>Crear rol y permisos</h2><p>Selecciona los módulos y acciones que tendrá este nuevo rol.</p></div></div><form method="POST" action="{{ route('admin.roles.store') }}" class="role-create-form ajax-form" data-reset-on-success="1">@csrf<label>Nombre del rol<input name="name" required placeholder="Ej. Supervisor de puerta"></label><div class="permission-grid">@foreach($pages as $page)<div class="module-permission-card"><label class="module-toggle"><input type="checkbox" name="page_ids[]" value="{{ $page->idPagina }}"><span><b>{{ $page->nombre }}</b><small>Acceso al módulo</small></span></label><div class="module-actions">@foreach($page->acciones as $action)<label><input type="checkbox" name="action_ids[]" value="{{ $action->idAccion }}"><span>{{ $action->descripcion ?: $action->nombre_Accion }}</span></label>@endforeach</div></div>@endforeach</div><button class="login-primary">Crear rol con permisos</button></form><hr class="roles-divider"><h3 class="created-title">Roles personalizados creados</h3><div class="role-list">@forelse($roles as $item)@include('auth.partials.role-card',['item'=>$item])@empty<p class="role-empty" data-empty-placeholder>Aún no hay roles personalizados.</p>@endforelse</div></section>
</section>
<div class="admin-heading role-users-heading"><div><p>PERSONAL REGISTRADO</p><h1>Asignar o cambiar rol</h1><span>El rol controla los módulos y acciones disponibles para cada usuario.</span></div></div><div class="user-admin-list role-user-list" id="roleAssignmentsList">@foreach($users as $item)@include('auth.partials.role-assignment-row',['item'=>$item,'roles'=>$assignableRoles])@endforeach</div>
</main></div><div class="toast" id="moduleToast"><span>✓</span><div><strong>Acción completada</strong><p>Los cambios se guardaron correctamente.</p></div></div></body></html>
