@php
$meta = [
 'citas' => ['tag'=>'AGENDA DEL DÍA','title'=>'Citas programadas','desc'=>'Consulta y administra los exámenes agendados para hoy.','action'=>'＋ Nueva cita'],
 'pacientes' => ['tag'=>'DIRECTORIO','title'=>'Buscar paciente','desc'=>'Verifica la identidad y las próximas citas de un paciente.','action'=>'⌕ Buscar'],
 'accesos' => ['tag'=>'CONTROL DE PUERTA','title'=>'Registrar ingreso o salida','desc'=>'Registra los movimientos de pacientes, acompañantes y visitantes.','action'=>'Ver historial'],
 'historial' => ['tag'=>'CONTROL DE ACCESO','title'=>'Historial de ingresos','desc'=>'Revisa los ingresos registrados en las puertas del hospital.','action'=>'⇩ Exportar'],
 'configuracion' => ['tag'=>'PREFERENCIAS','title'=>'Configuración del puesto','desc'=>'Personaliza el punto de control y las notificaciones.','action'=>'Guardar cambios'],
 'ayuda' => ['tag'=>'CENTRO DE AYUDA','title'=>'¿Cómo podemos ayudarte?','desc'=>'Encuentra respuestas rápidas para operar el sistema.','action'=>'Contactar soporte'],
][$module];
@endphp
<!DOCTYPE html><html lang="es"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>{{ $meta['title'] }} | Hospital La Merced Paita</title><link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link href="https://fonts.googleapis.com/css2?family=DM+Sans:wght@400;500;600;700&family=Manrope:wght@600;700;800&display=swap" rel="stylesheet">@vite(['resources/css/app.css','resources/js/app.js'])</head>
<body><div class="app-shell">
<aside class="sidebar" id="sidebar"><div class="brand"><div class="brand-mark"><img src="{{ asset('logo-hospital-la-merced.png') }}" alt="Logo del Hospital La Merced Paita"></div><div><strong>Hospital La Merced</strong><small>Paita · Piura</small></div></div>
<nav aria-label="Navegación principal"><a class="nav-item" href="{{ route('inicio') }}"><span class="nav-icon">⌂</span>Inicio</a><a class="nav-item {{ $module==='citas'?'active':'' }}" href="{{ route('citas') }}"><span class="nav-icon">▣</span>Citas del día <b>18</b></a><a class="nav-item {{ $module==='pacientes'?'active':'' }}" href="{{ route('pacientes') }}"><span class="nav-icon">⌕</span>Buscar paciente</a><a class="nav-item {{ $module==='accesos'?'active':'' }}" href="{{ route('accesos') }}"><span class="nav-icon">⇄</span>Registrar acceso</a><a class="nav-item {{ $module==='historial'?'active':'' }}" href="{{ route('historial') }}"><span class="nav-icon">◷</span>Historial</a></nav>
<div class="side-divider"></div><p class="nav-label">GESTIÓN</p><nav><a class="nav-item {{ $module==='configuracion'?'active':'' }}" href="{{ route('configuracion') }}"><span class="nav-icon">⚙</span>Configuración</a><a class="nav-item {{ $module==='ayuda'?'active':'' }}" href="{{ route('ayuda') }}"><span class="nav-icon">?</span>Ayuda</a></nav>
<div class="shift-card"><span class="shift-dot"></span><div><small>TURNO ACTIVO</small><strong>07:00 — 15:00</strong><p>Puerta principal</p></div></div><div class="profile"><div class="avatar">CM</div><div><strong>Carlos Mendoza</strong><small>Control de acceso</small></div></div></aside>
<main><header class="topbar"><button class="menu-btn" id="menuBtn" aria-label="Abrir menú">☰</button><div class="mobile-brand"><img src="{{ asset('logo-hospital-la-merced.png') }}" alt=""> La Merced Paita</div><div class="top-actions"><span class="live"><i></i>Sistema operativo</span><button class="icon-btn">♢<em>2</em></button><div class="today"><small>MIÉRCOLES</small><strong>05 AGO 2026</strong></div></div></header>
<div class="content module-content"><section class="hero module-hero"><div><p class="eyebrow">{{ $meta['tag'] }}</p><h1>{{ $meta['title'] }}</h1><p>{{ $meta['desc'] }}</p></div><button class="primary-btn moduleAction" @if($module==='accesos') data-url="{{ route('historial') }}" @endif>{{ $meta['action'] }}</button></section>

@if($module==='citas')
<section class="module-metrics"><article><small>TOTAL DE HOY</small><strong>18</strong><p>5 tipos de examen</p></article><article><small>MAÑANA</small><strong>24</strong><p>Agenda abierta</p></article><article><small>ESTA SEMANA</small><strong>96</strong><p>76% de ocupación</p></article></section>
<section class="panel"><div class="panel-toolbar"><div class="date-switch"><button>‹</button><strong>Miércoles, 05 de agosto</strong><button>›</button></div><select><option>Todos los servicios</option><option>Diagnóstico por imágenes</option><option>Laboratorio</option></select></div><div class="schedule-list">
@foreach([['08:30','María López Torres','Laboratorio','Ingresó'],['09:15','Jorge Salazar Peña','Resonancia magnética','Con retraso'],['09:40','Ana Ruiz Mendoza','Tomografía','Por llegar'],['10:00','Luis Paredes Silva','Ecografía','Por llegar'],['10:30','Carmen Díaz Rojas','Rayos X','Por llegar']] as $item)
<article><time>{{ $item[0] }}</time><div class="schedule-line"></div><div class="avatar">{{ collect(explode(' ',$item[1]))->map(fn($x)=>$x[0])->take(2)->join('') }}</div><div class="schedule-info"><strong>{{ $item[1] }}</strong><p>{{ $item[2] }} · Puerta principal</p></div><span class="status {{ Str::slug($item[3]) }}">{{ $item[3] }}</span><button class="row-action">Ver cita ›</button></article>@endforeach
</div></section>
@elseif($module==='pacientes')
<section class="search-hero"><p>Ingresa los datos del paciente</p><div><label><small>DNI DEL PACIENTE</small><input id="patientSearch" maxlength="8" placeholder="Ej. 45872931"></label><span>o</span><label><small>NOMBRE O APELLIDO</small><input id="patientName" placeholder="Ej. Ana Ruiz"></label><button id="patientButton">Buscar paciente</button></div></section>
<section class="panel patient-result" id="patientResult"><div class="result-head"><div class="avatar patient-avatar">AR</div><div><h2>Ana Ruiz Mendoza</h2><p>DNI 45872931 · 34 años · Paciente activo</p></div><span class="verified">✓ Identidad verificada</span></div><div class="patient-columns"><div><small>PRÓXIMA CITA</small><h3>Tomografía de tórax</h3><p>Hoy · 09:40 · Piso 1, Sala 108</p><button class="outline-btn">Ver detalle de cita</button></div><div><small>INFORMACIÓN DE CONTACTO</small><p>Teléfono: 987 432 106</p><p>Contacto: Elena Mendoza</p><p>Seguro: SaludPlus</p></div></div></section>
@elseif($module==='accesos')
<div class="access-layout">
<section class="panel access-form"><div class="access-type" role="tablist"><button type="button" class="active" data-access-type="Ingreso"><span>→</span><div><strong>Registrar ingreso</strong><small>Entrada al hospital</small></div></button><button type="button" data-access-type="Salida"><span>←</span><div><strong>Registrar salida</strong><small>Salida del hospital</small></div></button></div>
<form id="accessForm"><input type="hidden" id="movementType" value="Ingreso"><div class="form-section"><div class="form-section-title"><span>1</span><div><strong>Identificación de la persona</strong><p>Busca por DNI para completar los datos.</p></div></div><label class="dni-search"><span>DNI</span><div><input id="accessDni" required maxlength="8" inputmode="numeric" placeholder="Ingresa 8 dígitos"><button type="button" id="verifyDni">Consultar</button><button type="button" id="scanDni" class="scan-dni">▦ Escanear</button></div><small id="dniHint">Escribe el número o escanea el código del documento.</small></label><div class="identified-person" id="identifiedPerson" hidden><div class="avatar" id="identifiedInitials">--</div><div><strong id="identifiedName">Consultando...</strong><p id="identifiedDni">DNI</p></div><span>✓ Verificado</span></div></div>
<div class="form-section"><div class="form-section-title"><span>2</span><div><strong>Datos del movimiento</strong><p>Selecciona el motivo y el punto de acceso.</p></div></div><div class="form-grid"><label><span>Tipo de persona</span><select id="personType" required><option>Paciente</option><option>Acompañante</option><option>Visitante</option><option>Personal</option><option>Proveedor</option></select></label><label><span>Motivo</span><select id="accessReason" required><option>Examen programado</option><option>Consulta médica</option><option>Visita a paciente</option><option>Emergencia</option><option>Trámite administrativo</option></select></label><label><span>Punto de acceso</span><select id="accessPoint"><option>Puerta principal</option><option>Puerta norte</option><option>Emergencia</option><option>Estacionamiento</option></select></label><label><span>Número de acompañantes</span><input id="companions" type="number" min="0" max="5" value="0"></label></div><label class="notes-label"><span>Observaciones <small>(opcional)</small></span><textarea id="accessNotes" rows="3" placeholder="Añade una observación relevante..."></textarea></label></div>
<div class="access-confirm"><div><span id="currentTime">09:32</span><small>Hora de registro</small></div><button class="confirm-btn" id="registerAccess" disabled>Confirmar ingreso</button></div></form></section>
<aside class="access-side"><section class="access-summary"><small>PERSONAS DENTRO</small><strong>11</strong><div><span>Pacientes <b>7</b></span><span>Visitantes <b>4</b></span></div></section><section class="panel recent-access"><div class="recent-head"><h3>Movimientos recientes</h3><a href="{{ route('historial') }}">Ver todos</a></div><div id="recentAccessList">@foreach([['09:26','Diego Vásquez','Salida'],['09:18','Jorge Salazar','Ingreso'],['09:02','Elena Campos','Ingreso'],['08:47','Roberto Acosta','Salida']] as $r)<article><span class="recent-arrow {{ strtolower($r[2]) }}">{{ $r[2]==='Ingreso'?'→':'←' }}</span><div><strong>{{ $r[1] }}</strong><p>{{ $r[2] }} · Puerta principal</p></div><time>{{ $r[0] }}</time></article>@endforeach</div></section><div class="access-tip"><span>!</span><div><strong>Recuerda verificar la identidad</strong><p>Confirma que el documento corresponda a la persona antes de registrar el movimiento.</p></div></div></aside></div>
@elseif($module==='historial')
<section class="module-metrics"><article><small>INGRESOS HOY</small><strong>42</strong><p>11 por exámenes</p></article><article><small>SALIDAS</small><strong>31</strong><p>Última hace 4 min</p></article><article><small>DENTRO DEL HOSPITAL</small><strong>11</strong><p>Accesos activos</p></article></section>
<section class="panel"><div class="history-filters"><input id="historySearch" placeholder="⌕  Buscar por nombre o DNI"><input type="date" value="2026-08-05"><select id="accessFilter"><option value="">Todos los movimientos</option><option>Ingreso</option><option>Salida</option></select></div><div class="history-table"><table><thead><tr><th>FECHA Y HORA</th><th>PERSONA</th><th>MOVIMIENTO</th><th>ACCESO</th><th>MOTIVO</th></tr></thead><tbody id="historyBody">
@foreach([['08:32','María López Torres','Ingreso','Puerta principal','Examen'],['08:47','Roberto Acosta','Salida','Puerta norte','Consulta'],['09:02','Elena Campos','Ingreso','Puerta principal','Visita'],['09:18','Jorge Salazar Peña','Ingreso','Puerta principal','Examen'],['09:26','Diego Vásquez','Salida','Emergencia','Alta médica']] as $h)<tr data-movement="{{ $h[2] }}"><td><strong>05 AGO 2026</strong><small>{{ $h[0] }}</small></td><td><strong>{{ $h[1] }}</strong><small>DNI {{ rand(30000000,79999999) }}</small></td><td><span class="movement {{ strtolower($h[2]) }}">{{ $h[2]==='Ingreso'?'→':'←' }} {{ $h[2] }}</span></td><td>{{ $h[3] }}</td><td>{{ $h[4] }}</td></tr>@endforeach
</tbody></table></div></section>
@elseif($module==='configuracion')
<div class="settings-layout"><nav class="settings-nav"><button class="active">Puesto de control</button><button>Notificaciones</button><button>Visualización</button><button>Seguridad</button></nav><section class="panel settings-panel"><div class="settings-title"><h2>Puesto de control</h2><p>Información visible en los registros de ingreso.</p></div><form id="settingsForm"><div class="form-grid"><label><span>Nombre del puesto</span><input value="Puerta principal"></label><label><span>Código interno</span><input value="ACC-001"></label><label><span>Responsable del turno</span><input value="Carlos Mendoza"></label><label><span>Horario del turno</span><select><option>07:00 — 15:00</option><option>15:00 — 23:00</option></select></label></div><hr><div class="setting-row"><div><strong>Confirmación antes de registrar</strong><p>Solicitar confirmación para cada ingreso.</p></div><label class="switch"><input type="checkbox" checked><span></span></label></div><div class="setting-row"><div><strong>Alerta de citas retrasadas</strong><p>Mostrar una alerta pasados 10 minutos.</p></div><label class="switch"><input type="checkbox" checked><span></span></label></div><button class="primary-btn">Guardar configuración</button></form></section></div>
@else
<section class="help-search"><input id="helpSearch" placeholder="⌕  Escribe tu pregunta o busca un tema..."></section><section class="help-grid">@foreach([['▣','Citas y exámenes','Consultar, verificar y registrar citas.'],['⌕','Pacientes','Búsqueda por DNI y validación de identidad.'],['→','Control de ingreso','Registro de entradas, salidas y visitantes.'],['⚙','Configuración','Ajustes del puesto y notificaciones.']] as $help)<article><span>{{ $help[0] }}</span><h3>{{ $help[1] }}</h3><p>{{ $help[2] }}</p><a href="#">Ver artículos ›</a></article>@endforeach</section><section class="panel faq"><h2>Preguntas frecuentes</h2>@foreach(['¿Cómo confirmo el ingreso de un paciente?','¿Qué hago si la cita no aparece en el sistema?','¿Cómo registro a un acompañante?','¿Puedo corregir un ingreso registrado?'] as $q)<details><summary>{{ $q }}<span>＋</span></summary><p>Verifica primero el DNI y el código de cita. Si los datos son correctos, selecciona la cita y utiliza la acción correspondiente. Ante una inconsistencia, contacta a Admisión.</p></details>@endforeach</section>
@endif
<footer><p>Hospital La Merced Paita · Control de acceso</p><p><span></span> Conexión segura · Datos actualizados en tiempo real</p></footer></div></main></div><div class="toast" id="moduleToast"><span>✓</span><div><strong>Acción completada</strong><p>Los cambios se guardaron correctamente.</p></div></div></body></html>
