@php
$roleNames=['portero'=>'Portería','admision'=>'Admisión y citas','profesional'=>'Profesional de salud','laboratorio'=>'Laboratorio clínico','imagenes'=>'Diagnóstico por imágenes','administrador'=>'Administración'];
@endphp
<!DOCTYPE html><html lang="es"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><meta name="csrf-token" content="{{ csrf_token() }}"><title>{{ $roleNames[$role] }} | Hospital La Merced Paita</title><link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link href="https://fonts.googleapis.com/css2?family=DM+Sans:wght@400;500;600;700&family=Manrope:wght@600;700;800&display=swap" rel="stylesheet">@vite(['resources/css/app.css','resources/js/app.js'])</head><body>
<div class="hospital-portal"><aside class="role-sidebar"><a class="role-brand" href="{{ route('inicio') }}"><img src="{{ asset('logo-hospital-la-merced.png') }}" alt="Logo"><div><strong>Hospital La Merced</strong><small>Paita · Piura</small></div></a><p class="role-caption">MÓDULOS POR ROL</p><nav>@foreach($roleNames as $key=>$name)<a href="{{ route('portal',$key) }}" class="{{ $role===$key?'active':'' }}"><span>{{ ['portero'=>'⇄','admision'=>'▣','profesional'=>'✚','laboratorio'=>'◉','imagenes'=>'◫','administrador'=>'⚙'][$key] }}</span>{{ $name }}</a>@endforeach</nav><div class="role-user"><div class="avatar">{{ strtoupper(substr($roleNames[$role],0,2)) }}</div><div><strong>{{ $roleNames[$role] }}</strong><small>Sesión demostrativa</small></div></div></aside>
<main class="portal-main"><header class="portal-top"><button id="roleMenu" class="menu-btn">☰</button><div><small>ROL ACTIVO</small><strong>{{ strtoupper($roleNames[$role]) }}</strong></div><a href="{{ route('inicio') }}">Volver al inicio</a></header><div class="portal-content">
<section class="portal-heading"><div><p>HOSPITAL LA MERCED PAITA</p><h1>{{ $roleNames[$role] }}</h1><span>@if($role==='portero')Busca al paciente y verifica todas sus citas y exámenes antes de autorizar el ingreso.@elseif($role==='admision')Gestiona citas médicas, exámenes e interconsultas.@elseif($role==='profesional')Genera órdenes, revisa pacientes y solicita interconsultas según tu servicio.@elseif($role==='laboratorio')Controla muestras de sangre, orina y otros análisis clínicos.@elseif($role==='imagenes')Gestiona radiografías, tomografías, ecografías y resonancias.@elseSupervisa servicios, usuarios, roles y actividad del sistema.@endif</span></div><div class="portal-date">05<small>AGO 2026</small></div></section>
<section class="portal-stats"><article><span>▣</span><div><small>CITAS HOY</small><strong>{{ $metrics['citas_hoy'] }}</strong></div></article><article><span>●</span><div><small>LABORATORIO</small><strong>{{ $metrics['laboratorio'] }}</strong></div></article><article><span>◫</span><div><small>IMÁGENES</small><strong>{{ $metrics['imagenes'] }}</strong></div></article><article><span>⇢</span><div><small>INTERCONSULTAS</small><strong>{{ $metrics['interconsultas'] }}</strong></div></article></section>

@if($role==='portero')
<section class="portal-panel porter-search"><div class="panel-title"><div><h2>Buscar paciente</h2><p>Consulta por DNI para mostrar todas las citas vigentes.</p></div><span class="secure-badge">● Consulta segura</span></div><div class="porter-form"><label><span>DNI DEL PACIENTE</span><div><input id="portalDni" maxlength="8" inputmode="numeric" placeholder="Ingresa 8 dígitos"><button id="portalSearch">Buscar citas</button></div></label></div><div id="portalPatientResult" class="portal-patient" hidden></div></section>
<section class="portal-panel"><div class="panel-title"><div><h2>Citas y exámenes de hoy</h2><p>Agenda consolidada de todos los servicios.</p></div></div><div class="portal-table"><table><thead><tr><th>HORA</th><th>PACIENTE</th><th>SERVICIO</th><th>PROCEDIMIENTO</th><th>UBICACIÓN</th><th>ESTADO</th></tr></thead><tbody>@foreach($today as $a)<tr><td><strong>{{ $a->scheduled_at->format('H:i') }}</strong></td><td><strong>{{ $a->patient->full_name }}</strong><small>DNI {{ $a->patient->dni }}</small></td><td><span class="service-tag {{ $a->type->service->category }}">{{ $a->type->service->name }}</span></td><td>{{ $a->type->name }}</td><td>{{ $a->room }}</td><td><span class="status {{ $a->status }}">{{ ucfirst($a->status) }}</span></td></tr>@endforeach</tbody></table></div></section>
@elseif($role==='admision')
<section class="quick-actions"><button>＋ Agendar cita médica<small>Consulta por especialidad</small></button><button>＋ Agendar examen<small>Laboratorio o imágenes</small></button><button>⇢ Gestionar interconsulta<small>Entre servicios clínicos</small></button></section><section class="portal-grid"><div class="portal-panel"><div class="panel-title"><div><h2>Agenda general</h2><p>Citas programadas para hoy.</p></div><button class="outline-btn">Nueva cita</button></div><div class="compact-list">@foreach($today as $a)<article><time>{{ $a->scheduled_at->format('H:i') }}</time><div><strong>{{ $a->patient->full_name }}</strong><p>{{ $a->type->name }} · {{ $a->type->service->name }}</p></div><span>{{ ucfirst($a->status) }}</span></article>@endforeach</div></div><div class="portal-panel"><div class="panel-title"><div><h2>Interconsultas pendientes</h2><p>Solicitudes entre servicios.</p></div></div><div class="compact-list">@foreach($referrals as $r)<article><span class="round-icon">⇢</span><div><strong>{{ $r->first_names }} {{ $r->last_names }}</strong><p>{{ $r->origin_name }} → {{ $r->destination_name }}</p></div><span>{{ ucfirst($r->priority) }}</span></article>@endforeach</div></div></section>
@elseif($role==='profesional')
<section class="quick-actions"><button>＋ Nueva orden de laboratorio<small>Sangre, orina y otros</small></button><button>＋ Orden de imágenes<small>RX, TAC, ECO o RM</small></button><button>⇢ Solicitar interconsulta<small>Derivar a otra especialidad</small></button></section><section class="portal-grid"><div class="portal-panel"><div class="panel-title"><div><h2>Mis pacientes de hoy</h2><p>Medicina general.</p></div></div><div class="compact-list">@foreach($today->take(5) as $a)<article><time>{{ $a->scheduled_at->format('H:i') }}</time><div><strong>{{ $a->patient->full_name }}</strong><p>{{ $a->type->name }}</p></div><button class="outline-btn">Abrir ficha</button></article>@endforeach</div></div><div class="portal-panel"><div class="panel-title"><div><h2>Órdenes recientes</h2><p>Seguimiento por servicio.</p></div></div><div class="compact-list">@foreach($orders as $o)<article><span class="round-icon">{{ $o->service_id==1?'●':'◫' }}</span><div><strong>{{ $o->first_names }} {{ $o->last_names }}</strong><p>{{ $o->service_name }} · {{ $o->code }}</p></div><span>{{ ucfirst($o->status) }}</span></article>@endforeach</div></div></section>
@elseif(in_array($role,['laboratorio','imagenes']))
<section class="service-tabs">@if($role==='laboratorio')<button class="active">Todos</button><button>Sangre</button><button>Orina</button><button>Bioquímica</button>@else<button class="active">Todos</button><button>Radiografías</button><button>Tomografías</button><button>Ecografías</button><button>Resonancias</button>@endif</section><section class="portal-panel"><div class="panel-title"><div><h2>Cola de trabajo del servicio</h2><p>Pacientes programados y estado del procedimiento.</p></div><button class="outline-btn">Actualizar agenda</button></div><div class="portal-table"><table><thead><tr><th>HORA</th><th>PACIENTE</th><th>PROCEDIMIENTO</th><th>PREPARACIÓN / MUESTRA</th><th>ESTADO</th><th></th></tr></thead><tbody>@foreach($today as $a)<tr><td><strong>{{ $a->scheduled_at->format('H:i') }}</strong></td><td><strong>{{ $a->patient->full_name }}</strong><small>{{ $a->patient->dni }}</small></td><td>{{ $a->type->name }}</td><td>{{ $a->type->preparation }}</td><td><span class="status {{ $a->status }}">{{ ucfirst($a->status) }}</span></td><td><button class="outline-btn">Procesar</button></td></tr>@endforeach</tbody></table></div></section>
@else
<section class="admin-services">@foreach($services as $service)<article><span>{{ ['laboratorio'=>'●','imagenes'=>'◫','consulta'=>'✚','administrativo'=>'⚙'][$service->category] }}</span><div><h3>{{ $service->name }}</h3><p>{{ $service->location }}</p></div><b>{{ strtoupper($service->code) }}</b></article>@endforeach</section><section class="portal-panel"><div class="panel-title"><div><h2>Roles configurados</h2><p>Permisos y alcance por perfil.</p></div><button class="outline-btn">Gestionar usuarios</button></div><div class="roles-matrix"><div><strong>Portero</strong><p>Buscar pacientes, consultar citas y registrar accesos.</p></div><div><strong>Admisión</strong><p>Agendar citas, exámenes e interconsultas.</p></div><div><strong>Profesional</strong><p>Órdenes médicas, atención e interconsultas.</p></div><div><strong>Laboratorio / Imágenes</strong><p>Procesar órdenes y registrar resultados del servicio.</p></div></div></section>
@endif
</div></main></div><div class="toast" id="portalToast"><span>✓</span><div><strong>Registro completado</strong><p>La información se guardó correctamente.</p></div></div></body></html>
