@php
$moduleNames=['portero'=>'Portería y confirmación','citas'=>'Registro de citas','servicio'=>'Atención profesional','administrador'=>'Administración'];
$moduleIcons=['portero'=>'⇄','citas'=>'▣','servicio'=>'✚','administrador'=>'⚙'];
@endphp
<!DOCTYPE html><html lang="es"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="csrf-token" content="{{ csrf_token() }}"><title>{{ $moduleNames[$role] }} | Hospital La Merced Paita</title><link href="https://fonts.googleapis.com/css2?family=DM+Sans:wght@400;500;600;700&family=Manrope:wght@600;700;800&display=swap" rel="stylesheet">@vite(['resources/css/app.css','resources/js/app.js'])</head><body>
<div class="hospital-portal"><aside class="role-sidebar"><a class="role-brand" href="{{ route('inicio') }}"><img src="{{ asset('logo-hospital-la-merced.png') }}" alt="Logo"><div><strong>Hospital La Merced</strong><small>Paita · Piura</small></div></a><p class="role-caption">MÓDULOS AUTORIZADOS</p><nav>@foreach($moduleNames as $key=>$name)@if($user->canAccessModule($key))<a href="{{ route('portal',$key) }}" class="{{ $role===$key?'active':'' }}"><span>{{ $moduleIcons[$key] }}</span>{{ $name }}</a>@endif @endforeach</nav><div class="role-user"><div class="avatar">@if($user->photo_path)<img src="{{ route('profile.photo') }}?v={{ $user->updated_at->timestamp }}" alt="Foto de {{ $user->name }}">@else{{ strtoupper(substr($user->name,0,2)) }}@endif</div><div><strong>{{ $user->name }}</strong><small>{{ $user->customRole?->name ?? ucfirst($user->role) }}</small></div></div></aside>
<main class="portal-main"><header class="portal-top"><button id="roleMenu" class="menu-btn">☰</button><div><small>MÓDULO ACTIVO</small><strong>{{ strtoupper($moduleNames[$role]) }}</strong></div><div class="user-menu"><button type="button" id="userMenuButton" class="user-menu-trigger" aria-expanded="false"><span class="user-menu-photo">@if($user->photo_path)<img src="{{ route('profile.photo') }}?v={{ $user->updated_at->timestamp }}" alt="Foto">@else{{ strtoupper(substr($user->name,0,2)) }}@endif</span><span><strong>{{ $user->name }}</strong><small>{{ $user->customRole?->name ?? ucfirst($user->role) }}</small></span><i>⌄</i></button><div class="user-dropdown" id="userDropdown" hidden><div class="user-dropdown-head"><b>{{ $user->name }}</b><span>{{ $user->email }}</span></div><a href="{{ route('account.settings') }}">⚙ Configuración de cuenta</a>@if($user->role==='administrador')<a href="{{ route('admin.roles') }}">♙ Roles y permisos</a><a href="{{ route('admin.users') }}">▦ Gestionar usuarios</a>@endif<form method="POST" action="{{ route('logout') }}">@csrf<button>↪ Cerrar sesión</button></form></div></div></header>
<div class="portal-content">@if(session('success'))<div class="success-banner">✓ {{ session('success') }}</div>@endif
<section class="portal-heading"><div><p>HOSPITAL LA MERCED PAITA</p><h1>{{ $moduleNames[$role] }}</h1><span>@if($role==='portero') Verifica la cita y confirma la llegada del paciente. @elseif($role==='citas') Registra al paciente, fecha, hora, servicio y profesional responsable. @elseif($role==='servicio') Muestra únicamente los pacientes destinados al servicio del usuario. @else Configura usuarios, roles y permisos de acceso a cada módulo. @endif</span></div><div class="portal-date">{{ now()->format('d') }}<small>{{ strtoupper(now()->translatedFormat('M Y')) }}</small></div></section>
<section class="portal-stats"><article><span>▣</span><div><small>CITAS HOY</small><strong>{{ $metrics['citas_hoy'] }}</strong></div></article><article><span>✓</span><div><small>CONFIRMADAS</small><strong>{{ $metrics['confirmadas'] }}</strong></div></article><article><span>→</span><div><small>INGRESOS</small><strong>{{ $metrics['ingresos'] }}</strong></div></article><article><span>◷</span><div><small>PENDIENTES</small><strong>{{ $metrics['pendientes'] }}</strong></div></article></section>

@if($role==='citas')
<section class="portal-panel appointment-register"><div class="panel-title"><div><h2>Registrar nueva cita</h2><p>La cita aparecerá automáticamente en la agenda del servicio seleccionado.</p></div></div><form method="POST" action="{{ route('appointments.store') }}" class="appointment-form">@csrf<label>DNI<input name="dni" maxlength="8" inputmode="numeric" required placeholder="8 dígitos"></label><label>Nombre completo<input name="patient_name" required placeholder="Nombres y apellidos"></label><label>Servicio y atención<select name="appointment_type_id" required><option value="">Seleccionar</option>@foreach($services as $service)<optgroup label="{{ $service->name }}">@foreach($service->appointmentTypes as $type)<option value="{{ $type->id }}">{{ $type->name }}</option>@endforeach</optgroup>@endforeach</select></label><label>Área / destino<select name="service_area_id"><option value="">Área general del servicio</option>@foreach($areas->groupBy('service.name') as $serviceName=>$serviceAreas)<optgroup label="{{ $serviceName }}">@foreach($serviceAreas as $area)<option value="{{ $area->id }}">{{ $area->name }}</option>@endforeach</optgroup>@endforeach</select></label><label>Profesional<select name="professional_id"><option value="">Por asignar</option>@foreach($professionals as $professional)<option value="{{ $professional->id }}">{{ $professional->name }} — {{ $professional->service?->name }}</option>@endforeach</select></label><label>Fecha y hora<input name="scheduled_at" type="datetime-local" required></label><label>Consultorio / ambiente<input name="room" placeholder="Ej. Consultorio 105"></label><label class="form-wide">Observaciones<textarea name="notes" rows="3" placeholder="Indicaciones para la atención"></textarea></label><button class="primary-btn form-wide">Registrar cita médica</button></form></section>
@elseif($role==='portero')
<section class="portal-panel porter-search"><div class="panel-title"><div><h2>Buscar paciente</h2><p>Consulta por DNI para mostrar todas sus citas vigentes.</p></div><span class="secure-badge">● Consulta segura</span></div><div class="porter-form"><label><span>DNI DEL PACIENTE</span><div><input id="portalDni" maxlength="8" inputmode="numeric" autocomplete="off" placeholder="Ingresa los 8 dígitos"><button type="button" id="portalSearch">Buscar citas</button></div></label></div><div id="portalPatientResult" class="portal-patient" hidden></div></section>
<section class="portal-panel"><div class="panel-title"><div><h2>Pacientes programados hoy</h2><p>Confirma la llegada antes de autorizar el ingreso.</p></div></div><div class="portal-table"><table><thead><tr><th>HORA</th><th>PACIENTE</th><th>SERVICIO</th><th>ATENCIÓN</th><th>ESTADO</th><th>ACCIÓN</th></tr></thead><tbody>@forelse($today as $a)<tr><td><strong>{{ $a->scheduled_at->format('H:i') }}</strong></td><td><strong>{{ $a->patient->full_name }}</strong><small>DNI {{ $a->patient->dni }}</small></td><td>{{ $a->type->service->name }}</td><td>{{ $a->type->name }}</td><td><span class="status {{ $a->status }}">{{ ucfirst($a->status) }}</span></td><td>@if($a->status==='programada')<form method="POST" action="{{ route('appointments.confirm',$a) }}">@csrf @method('PUT')<button class="confirm-small">Confirmar llegada</button></form>@else<span class="confirmed-label">✓ Verificada</span>@endif</td></tr>@empty<tr><td colspan="6" class="portal-empty">No hay citas programadas para hoy.</td></tr>@endforelse</tbody></table></div></section>
@elseif($role==='servicio')
<section class="portal-panel"><div class="panel-title"><div><h2>Pacientes de {{ $user->role==='administrador'?'todos los servicios':($user->service?->name ?? 'mi servicio') }}</h2><p>El profesional confirma la atención después de que Portería registre la llegada.</p></div></div><div class="portal-table"><table><thead><tr><th>HORA</th><th>PACIENTE</th><th>ATENCIÓN</th><th>PROFESIONAL</th><th>ESTADO</th><th>ACCIÓN</th></tr></thead><tbody>@forelse($today as $a)<tr><td><strong>{{ $a->scheduled_at->format('H:i') }}</strong></td><td><strong>{{ $a->patient->full_name }}</strong><small>{{ $a->patient->dni }}</small></td><td>{{ $a->type->name }}<small>{{ $a->type->service->name }}</small></td><td>{{ $a->professional?->name ?? $user->name }}</td><td><span class="status {{ $a->status }}">{{ ucfirst($a->status) }}</span></td><td>@if(in_array($a->status,['confirmada','ingreso']))<form method="POST" action="{{ route('appointments.complete',$a) }}">@csrf @method('PUT')<button class="confirm-small">Confirmar atención</button></form>@elseif($a->status==='atendida')<span class="confirmed-label">✓ Atendida</span>@else<span class="waiting-label">Esperando a Portería</span>@endif</td></tr>@empty<tr><td colspan="6" class="portal-empty">No hay pacientes programados para este profesional.</td></tr>@endforelse</tbody></table></div></section>
@else
<section class="quick-actions"><button data-url="{{ route('admin.catalog') }}" class="moduleAction">＋ Servicios y profesionales<small>Crea servicios y cuentas profesionales</small></button><button data-url="{{ route('admin.roles') }}" class="moduleAction">♙ Crear roles y permisos<small>Define acceso por módulo</small></button><button data-url="{{ route('portal','citas') }}" class="moduleAction">▣ Registrar una cita<small>Enviar paciente a un servicio</small></button></section><section class="portal-panel"><div class="panel-title"><div><h2>Servicios disponibles</h2><p>Los profesionales reciben solamente los pacientes correspondientes a su servicio.</p></div><a class="outline-btn" href="{{ route('admin.catalog') }}">Administrar</a></div><div class="admin-services">@foreach($services as $service)<article><span>✚</span><div><h3>{{ $service->name }}</h3><p>{{ $service->location }}</p></div><b>{{ $service->code }}</b></article>@endforeach</div></section>
@endif
</div></main></div></body></html>
